---
# Configuration file for MegaLinter
# See all available variables at https://megalinter.io/configuration/ and in linters documentation

DISABLE_LINTERS:
  - REPOSITORY_TRIVY
  - JAVA_PMD
  - CSS_STYLELINT
  - TYPESCRIPT_STANDARD
  - REPOSITORY_GIT_DIFF
  - DOCKERFILE_HADOLINT
  - REPOSITORY_DEVSKIM
  - REPOSITORY_TRUFFLEHOG
  - REPOSITORY_KICS
  - REPOSITORY_GRYPE

# Disable the "newline at end of file" rule
ESLINT_RULES:
  eol-last: "off"