package com.maxprofit.calculator;

import au.com.dius.pact.provider.junit5.HttpTestTarget;
import au.com.dius.pact.provider.junit5.PactVerificationContext;
import au.com.dius.pact.provider.junit5.PactVerificationInvocationContextProvider;
import au.com.dius.pact.provider.junitsupport.Provider;
import au.com.dius.pact.provider.junitsupport.loader.PactFolder;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.TestTemplate;
import org.junit.jupiter.api.extension.ExtendWith;

/**
 * Verifies the running backend against the pact generated by the frontend's
 * consumer tests ({@code site/frontend/pacts}, copied to
 * {@code target/test-classes/pacts} by the build), without a Pact Broker.
 * Uses Pact's own verifier, so the contract's matching rules apply exactly as
 * they do in {@link PactBrokerVerificationTest}.
 *
 * <p>Needs the API running on port 9095: {@code mvn test -Pcontract-tests}.
 */
@Provider("max-profit-calculator-backend")
@PactFolder("pacts")
public class LocalContractVerificationTest {

    @BeforeEach
    void setup(final PactVerificationContext context) {
        context.setTarget(new HttpTestTarget("localhost", 9095));
    }

    @TestTemplate
    @ExtendWith(PactVerificationInvocationContextProvider.class)
    void verifyPact(final PactVerificationContext context) {
        context.verifyInteraction();
    }
}
