version: '3.7'
services:
  app:
    build: ../../
    ports:
      - '9095:9095'
  site:
    build:
      context: .
      dockerfile: Dockerfile
      target: base
    ports:
      - '3000:3000'
    volumes:
      - ./src/:/home/node/app/src
    command: npm run dev
    depends_on:
      - app
