name: npm Update Checker
on:
  workflow_dispatch
jobs:
  npm:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - run: npm install
    - uses: MeilCli/npm-update-check-action@v4.0.0
      id: outdated      
