---
name: Yaml Lint
on: [push] # yamllint disable-line rule:truthy

run-name: Yaml Lint

permissions:
  contents: read

jobs:
  lintAllTheThings:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          persist-credentials: false

      - name: yaml-lint
        uses: ibiqlik/action-yamllint@2576378a8e339169678f9939646ee3ee325e845c # v3.1.1
        with:
          config_data: |
            extends: default
            rules:
              line-length:
                level: warning
                max: 150
              new-line-at-end-of-file:
                level: warning
              trailing-spaces:
                level: warning
